### ISSUE TITLE
failed to mmap

### ISSUE THREAD

**Issue by lightydo** [larytet/YALAS#7] opened 2017-03-07 15:58 UTC
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=4194304 tail=4194304, head=0
ERR Failed to mmap /sys/kernel/debug/yalas/syscalls_0 No such device

**Comment by larytet** [comment] 2017-03-08 06:04
Have you done 
   sudo make load
What do return commands 
  sudo ls /sys/kernel/debug/
  sudo ls /sys/kernel/debug/yalas

**Comment by larytet** [comment] 2017-03-08 06:22
For example commit 1c53b6317c9d331b on `Linux ubuntu 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` 
shall produce

```
$ make clean;make
gcc      -c -o src/cli/linenoise.o src/cli/linenoise.c
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/main.o src/main.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/cli/cli.o src/cli/cli.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/linux_utils.o src/linux_utils.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/big_filter.o src/big_filter.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/shm.o src/shm.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/stat.o src/stat.cpp
g++  -Isrc/emcpp -Isrc/cli -Isrc/driver -O2 -g -Wall -fmessage-length=0 -std=c++11      -c -o src/emcpp/HashTable.o src/emcpp/HashTable.cpp
WARNING: Kernel function symbol table missing [man warning::symbols]
Pass 1: parsed user script and 110 library script(s) using 105480virt/39804res/6308shr/33532data kb, in 110usr/0sys/119real ms.
Pass 2: analyzed script: 192 probe(s), 32 function(s), 107 embed(s), 17 global(s) using 269388virt/205144res/7732shr/197440data kb, in 2550usr/640sys/3212real ms.
Pass 3: translated to C into "/tmp/stapoan46i/yalas_drv_src.c" using 269388virt/205272res/7860shr/197440data kb, in 20usr/0sys/22real ms.
yalas_drv.ko
Pass 4: compiled C into "yalas_drv.ko" in 3660usr/320sys/4011real ms.
Keeping temporary directory "/tmp/stapoan46i"

$ sudo make load
rmmod yalas_drv
#@staprun ./yalas_drv.ko -L
insmod ./yalas_drv.ko
scripts/generate_messages.py -c /sys/kernel/debug/systemtap/yalas_drv/.cmd
STP_READY (8)
STP_PRIVILEGE_CREDENTIALS (15), see pr_all
STP_RELOCATION (can be .__start in PPC)
STAP_START (0)


$ sudo ls /sys/kernel/debug/
acpi  bluetooth  cleancache  dma_buf  dynamic_debug  fault_around_bytes  gpio  iosf_sb	mce	 pm_qos  ras	 regulator	 sleep_time	systemtap  usb		 vmmemctl	 x86	zswap
bdi   btrfs	 clk	     dri      extfrag	     frontswap		 hid   kprobes	pinctrl  pwm	 regmap  sched_features  suspend_stats	tracing    virtio-ports  wakeup_sources  yalas

$ sudo ls /sys/kernel/debug/yalas
syscalls_0  syscalls_1

```

**Comment by larytet** [comment] 2017-03-08 07:01
In the commit 5771134 command `sudo make NO_STAPRUN=1 load` will load the driver using staprun

**Comment by larytet** [comment] 2017-03-19 14:26
Duplicate of #8

**Closed by larytet** 2017-03-19 14:26 UTC
