### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lightydo** [larytet/YALAS#8] opened 2017-03-12 12:15 UTC
$> sudo ./yalas
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=16777216 tail=172960, head=0
INFOE Open file /sys/kernel/debug/yalas/syscalls_1 size=16777216 tail=85296, head=0
dbg/dbg
 dbg
  hashtables
  stat
  shm
  pool
  bf
   stat
 help
 exit
INFOE Init big filter
INFO Thread 'syscalls' is running
INFO Thread 'cli' is running
Segmentation fault

**Comment by larytet** [comment] 2017-03-13 08:05
Could you try 

`sudo gdb --args ./yalas`
followed by 

`run `

Thanks

**Comment by lightydo** [comment] 2017-03-13 08:07
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=16777216 tail=16777168, head=0
INFOE Open file /sys/kernel/debug/yalas/syscalls_1 size=16777216 tail=16777136, head=0
dbg/dbg
 dbg
  hashtables
  stat
  shm
  pool
  bf
   stat
 help
 exit
INFOE Init big filter
[New Thread 0x7ffff5b48700 (LWP 32729)]
INFO Thread 'syscalls' is running
[New Thread 0x7ffff5347700 (LWP 32730)]
INFO Thread 'cli' is running
/
 Thread 2 "yalas" received signal SIGSEGV, Segmentation fault.
                                                              [Switching to Thread 0x7ffff5b48700 (LWP 32729)]
bf_syscalls_task (args=<optimized out>) at src/big_filter.cpp:723
warning: Source file is more recent than executable.
723	    stat_counter_inc(STAT_COUNTER_BF_TASK_SLEEP);

**Comment by lightydo** [comment] 2017-03-13 08:20
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=16777216 tail=969184, head=0
INFOE Open file /sys/kernel/debug/yalas/syscalls_1 size=16777216 tail=996336, head=0
dbg/dbg
 dbg
  hashtables
  stat
  shm
  pool
  bf
   stat
 help
 exit
INFOE Init big filter
[New Thread 0x7ffff5b48700 (LWP 6230)]
INFO Thread 'syscalls' is running
[New Thread 0x7ffff5347700 (LWP 6231)]

Thread 2 "yalas" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5b48700 (LWP 6230)]
bf_syscalls_task (args=<optimized out>) at src/big_filter.cpp:723
723	    	const uint32_t fifo_size = SHM_FIFO_VOLATILE(fifo->descr.size);

**Comment by larytet** [comment] 2017-03-13 08:52
What is an output of command  `uname -a ` ?

**Comment by larytet** [comment] 2017-03-13 08:58
Most likely reason is a wrong kernel version. 
Try 
```
sudo apt-get install linux-image-$(uname -r)-dbgsym build-essential systemtap systemtap-runtime linux-headers-$(uname -r) 
make clean;make
sudo make load;
sudo ./yalas
```

**Comment by lightydo** [comment] 2017-03-13 09:06
I think the problem is in shm_open_trace(), the fifo_descr is not stored in the trace_file...

**Comment by lightydo** [comment] 2017-03-13 09:07
using ARCH. i have pinned my kernel, otherwise I will have to recompile it every time to get the debug symbols..

**Comment by lightydo** [comment] 2017-03-13 09:10
I'll double check myself

**Comment by larytet** [comment] 2017-03-13 09:24
The failure can be caused by a virtual page miss in the driver. Fetch of the 'size' is a first word in the FIFO structure. The call to MMAP apparently worked because the system prints the FIFO status - size, tail, head. The values look Ok - 16MB per FIFO.

**Comment by larytet** [comment] 2017-03-13 09:28
I am running tests on Ubuntu. I allow the security updates for the kernel. I am preparing a package which will update the driver automatically every time the kernel updates.

**Comment by lightydo** [comment] 2017-03-13 13:48
yes, the print is ok, but I don;t think it places what it fetches in the trace_file. 
Anyway, I downloaded and recompiled my kernel (4.10.1-1-ARCH), still same problem. 
I placed a log for the fifo in bf_syscalls_task()         

```
.....
linux_log(LINUX_LOG_INFO, "fifo = %p", fifo);
linux_log(LINUX_LOG_INFO, "fifo->descr.size = %d", fifo->descr.size);
....
```


here is the gdb output:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=16777216 tail=746128, head=0
INFOE Open file /sys/kernel/debug/yalas/syscalls_1 size=16777216 tail=455136, head=0
dbg/dbg
 dbg
  hashtables
  stat
  shm
  pool
  bf
   stat
 help
 exit
INFOE Init big filter
[New Thread 0x7ffff5b32700 (LWP 21830)]
INFO Thread 'syscalls' is running
INFOE fifo = 0xffffffffffffffff
[New Thread 0x7ffff5331700 (LWP 21833)]
INFO Thread 'cli' is running
/
 Thread 2 "yalas" received signal SIGSEGV, Segmentation fault.
                                                              [Switching to Thread 0x7ffff5b32700 (LWP 21830)]
0x00000000004079d9 in bf_syscalls_task (args=0x610ee0 <config_system_params>) at src/big_filter.cpp:724
724	        linux_log(LINUX_LOG_INFO, "fifo->descr.size = %d", fifo->descr.size);
```

as you can see the fifo has a bad address...

BTW, I found a error with the new kernel. the `struct vm_fault` was changed, so need to fix syscalls_trace_mmap_fault() in sysfs.c when accessing the virtual_address. 

```
#if LINUX_VERSION_CODE < KERNEL_VERSION(4,10,0)
    unsigned long address = (unsigned long)vmf->virtual_address;
#else
    unsigned long address = (unsigned long)vmf->address;
#endif
```

**Comment by larytet** [comment] 2017-03-13 14:10
Indeed function shm_open_trace() simply reads the trace files and prints the FIFO descriptor. Call to mmap() still can fail

**Comment by lightydo** [comment] 2017-03-13 15:07
ok, now we're back to "failed to mmap" reported in issue#7. 

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFOE Open file /sys/kernel/debug/yalas/syscalls_0 size=16777216 tail=1262720, head=0
ERR Failed to mmap /sys/kernel/debug/yalas/syscalls_0 No such device
dbg/dbg
 dbg
  hashtables
  stat
  shm
  pool
  bf
   stat
 help
 exit
INFOE Init big filter
[New Thread 0x7ffff5b32700 (LWP 23288)]
INFO Thread 'syscalls' is running
[New Thread 0x7ffff5331700 (LWP 23289)]
INFO Thread 'cli' is running
```

**Comment by larytet** [comment] 2017-03-13 15:47
What is an output of command `uname -a ?`

**Comment by lightydo** [comment] 2017-03-14 12:03
`Linux daniel-arch 4.10.1-1-ARCH #1 SMP PREEMPT Mon Mar 13 13:42:19 IST 2017 x86_64 GNU/Linux`

```
[82283.342939] yalas: remove_sysfs_folder called
[82283.342950] yalas: remove_syscalls_trace_files called
[82283.342962] yalas: remove_syscalls_shm called
[82283.737578] yalas_drv: systemtap: 3.2/0.168, base: ffffffffa060a000, memory: 220data/144text/9ctx/2063net/9431alloc kb, probes: 192
[82283.737694] yalas: create_sysfs_folder called
[82283.737700] yalas: create_syscalls_shm: cpus=2
[82283.737814] yalas: create_syscalls_trace_files called
[82283.738450] yalas: create_syscalls_trace_files: syscalls_0
[82283.739133] yalas: create_syscalls_trace_files: syscalls_1
```

**Comment by larytet** [comment] 2017-03-14 13:58
What does command `sudo find /sys -name syscalls_*` produce?

**Comment by lightydo** [comment] 2017-03-14 15:25
```
/sys/kernel/yalas/syscalls_trace_size
/sys/kernel/debug/yalas/syscalls_1
/sys/kernel/debug/yalas/syscalls_0
```

```
$> mount | grep debugfs
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
```

**Comment by larytet** [comment] 2017-03-14 16:00
I suspect that there is a bug in the kernel driver. I need time to bring up a VM with archlinux and try it.

**Comment by lightydo** [comment] 2017-03-15 10:17
ok. let me know if you want me to drop in some debug prints that can help.

**Comment by larytet** [comment] 2017-03-16 16:02
You can try to load the driver again and start the `./yalas`. See what the driver outputs in the kernel log. May be there is an error when attempting to map the virtual memory.

**Comment by larytet** [comment] 2017-03-16 16:08
Alternatively you can try to use `Linux ubuntu 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` which is currently the only system I run tests on.

**Comment by larytet** [comment] 2017-03-19 14:03
Reproduced in Ubuntu 16.10 `Linux ubuntu 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by larytet** [comment] 2017-03-19 14:41
`#define ENODEV          19      /* No such device */`

**Comment by larytet** [comment] 2017-03-19 15:12
Probably relevant https://lkml.org/lkml/2016/5/21/73

**Comment by larytet** [comment] 2017-03-21 07:44
I am closing the issue as fixed

**Closed by larytet** 2017-03-21 07:44 UTC
